apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hajimari
  namespace: hajimari
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`hajimari.home`)
      kind: Rule
      services:
        - name: hajimari
          kind: Service
          port: 3000
# TLS is disabled for now; enable when you have a certificate (cert-manager or secret)
