apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      # Use a modern chart version that contains CRDs compatible with recent Kubernetes
      # clusters. Adjust if you prefer a pinned release.
      version: "~> 20.0.0"
  interval: 1m0s
  install:
    createNamespace: false
  values:
    service:
      type: LoadBalancer
    ingressClass:
      enabled: true
      isDefaultClass: true
