apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      # Use a modern chart version that contains CRDs compatible with recent Kubernetes
      # clusters. Adjust if you prefer a pinned release.
      version: "~> 20.0.0"
  interval: 1m0s
  install:
    createNamespace: false
  values:
    service:
      type: NodePort
    ingressClass:
      enabled: true
      isDefaultClass: true
    dashboard:
      enabled: true
    # Prevent the chart from creating its own IngressRoute for the dashboard.
    # We keep the dashboard enabled so the internal api@internal and dashboard
    # are available, but disable the chart-owned IngressRoute so we can
    # manage routing (and middleware) declaratively in this repo.
    ingressRoute:
      dashboard:
        enabled: false
    additionalArguments:
      - "--api.dashboard=true"
      - "--api.insecure=false"
